export enum NotificationType {
  APPOINTMENT_CREATED = "APPOINTMENT_CREATED",
  APPOINTMENT_CONFIRMED = "APPOINTMENT_CONFIRMED",
  APPOINTMENT_CANCELLED = "APPOINTMENT_CANCELLED",
  APPOINTMENT_REMINDER = "APPOINTMENT_REMINDER",
  APPOINTMENT_REMINDER_24H = "APPOINTMENT_REMINDER_24H",
  APPOINTMENT_REMINDER_30M = "APPOINTMENT_REMINDER_30M",
  PAYMENT_SUCCESS = "PAYMENT_SUCCESS",
  PAYMENT_FAILED = "PAYMENT_FAILED",
  REFUND_PROCESSED = "REFUND_PROCESSED",
  REVIEW_RECEIVED = "REVIEW_RECEIVED",
  GENERAL = "GENERAL",
}

export interface Notification {
  id: string;
  userId: string;
  title: string;
  content: string;
  type: NotificationType;
  isRead: boolean;
  channel?: string;
  sentAt?: Date;
  createdAt: Date;
}
